apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vulnerable-demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Advit105/secure-supply-chain-pipeline.git # <-- point at your fork
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
